{% set version = "10.0.1" %}

package:
  name: kubernetes_asyncio
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/kubernetes_asyncio/kubernetes_asyncio-{{ version }}.tar.gz
  sha256: 3fbe4e33533a42b9aab0151d3bf1e887921e358a244e7ed2c45a78138fd046cd

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools >=21.0.0
    - aiohttp >=2.3.10
    - certifi >=14.05.14
    - python-dateutil >=2.5.3
    - pyyaml >=3.12
    - six >=1.9.0
    - urllib3 >=1.24.2

test:
  imports:
    - kubernetes_asyncio
    - kubernetes_asyncio.client
    - kubernetes_asyncio.client.api
    - kubernetes_asyncio.client.models
    - kubernetes_asyncio.config
    - kubernetes_asyncio.stream
    - kubernetes_asyncio.utils
    - kubernetes_asyncio.watch

about:
  home: "https://github.com/tomplus/kubernetes_asyncio"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Kubernetes asynchronous python client"

extra:
  recipe-maintainers:
    - ocefpaf
